### ISSUE TITLE
Broken links in matching service content

### ISSUE THREAD

**Issue by benjamin-mortimer** [alphagov/verify-tech-docs#41]
Quite a few of the links on the [Connecting to Verify with a compulsory matching service](https://www.docs.verify.service.gov.uk/legacy/connecting-compulsory-ms/#connecting-to-verify-with-a-compulsory-matching-service) page return 404s.

For example: 

"[Download and install the Matching Service Adapter](https://www.docs.verify.service.gov.uk/legacy/connecting-compulsory-ms/LINK)".

**Comment by owenblacker** [comment]
We have decommisioned these docs today; this issue is no longer pertinent
